# Apply after component registration, so each target's final source list exists.
# Generated files live in the normal IDF output; managed SDK sources are untouched.
function(gea_patch_streaming_dependencies)
    find_package(Python3 REQUIRED COMPONENTS Interpreter)
    # Espressif's libsrtp package defaults to its portable AES/SHA routines.
    # Selecting IDF hardware crypto alone does not accelerate those routines;
    # use libsrtp's existing mbedTLS backends when the app enables it.
    if(TARGET __idf_espressif__esp_libsrtp AND CONFIG_MBEDTLS_HARDWARE_AES)
        set(_srtp_target __idf_espressif__esp_libsrtp)
        get_target_property(_srtp_dir "${_srtp_target}" SOURCE_DIR)
        get_target_property(_srtp_sources "${_srtp_target}" SOURCES)
        set(_srtp_aes "${_srtp_dir}/libsrtp/crypto/cipher/aes_icm_mbedtls.c")
        set(_srtp_psa_hmac FALSE)
        if(IDF_VERSION_MAJOR GREATER_EQUAL 6 AND CONFIG_MBEDTLS_HARDWARE_SHA)
            set(_srtp_psa_hmac TRUE)
            target_include_directories("${_srtp_target}" PRIVATE "${_srtp_dir}/libsrtp/crypto/hash")
        endif()
        if(IDF_VERSION_MAJOR GREATER_EQUAL 6)
            set(_srtp_aes "${CMAKE_BINARY_DIR}/gea_srtp_aes.c")
            foreach(_aes_spec "srtp_aes|libsrtp/crypto/cipher/aes_icm_mbedtls.c|gea_srtp_aes.c"
                              "srtp_aes_header|libsrtp/crypto/include/aes_icm_ext.h|gea_srtp_aes_icm.h")
                string(REPLACE "|" ";" _aes_parts "${_aes_spec}")
                list(GET _aes_parts 0 _aes_kind)
                list(GET _aes_parts 1 _aes_source)
                list(GET _aes_parts 2 _aes_output)
                execute_process(COMMAND "${Python3_EXECUTABLE}"
                    "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/patch_streaming_dependencies.py"
                    "${_aes_kind}" "${_srtp_dir}/${_aes_source}" "${CMAKE_BINARY_DIR}/${_aes_output}"
                    COMMAND_ERROR_IS_FATAL ANY)
            endforeach()
            target_include_directories("${_srtp_target}" PRIVATE "${CMAKE_BINARY_DIR}"
                "${_srtp_dir}/libsrtp/crypto/cipher")
        endif()
        set(_srtp_replacement "")
        foreach(_source IN LISTS _srtp_sources)
            if(_source MATCHES "(^|/)libsrtp/crypto/cipher/aes\\.c$")
                continue()
            elseif((IDF_VERSION_MAJOR LESS 6 OR _srtp_psa_hmac) AND _source MATCHES "(^|/)libsrtp/crypto/hash/sha1\\.c$")
                continue()
            elseif(_source MATCHES "(^|/)libsrtp/crypto/cipher/aes_icm\\.c$")
                list(APPEND _srtp_replacement "${_srtp_aes}")
            elseif(_source MATCHES "(^|/)libsrtp/crypto/hash/hmac\\.c$")
                if(_srtp_psa_hmac)
                    list(APPEND _srtp_replacement "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/crypto/srtp_hmac_psa.c")
                elseif(IDF_VERSION_MAJOR LESS 6)
                    list(APPEND _srtp_replacement "${_srtp_dir}/libsrtp/crypto/hash/hmac_mbedtls.c")
                else()
                    list(APPEND _srtp_replacement "${_source}")
                endif()
            else()
                list(APPEND _srtp_replacement "${_source}")
            endif()
        endforeach()
        set_property(TARGET "${_srtp_target}" PROPERTY SOURCES "${_srtp_replacement}")
        target_compile_definitions("${_srtp_target}" PRIVATE MBEDTLS)
        target_link_libraries("${_srtp_target}" PUBLIC idf::mbedtls)
        message(STATUS "Gea SRTP: hardware AES-ICM enabled, PSA HMAC=${_srtp_psa_hmac}")
    endif()
    foreach(_spec "websocket|espressif__esp_websocket_client|esp_websocket_client.c"
                  "ws_transport|tcp_transport|transport_ws.c"
                  "codec|espressif__esp_codec_dev|platform/audio_codec_data_i2s.c")
        string(REPLACE "|" ";" _parts "${_spec}")
        list(GET _parts 0 _kind)
        list(GET _parts 1 _component)
        list(GET _parts 2 _relative)
        set(_target "__idf_${_component}")
        if(NOT TARGET "${_target}")
            continue()
        endif()
        get_target_property(_dir "${_target}" SOURCE_DIR)
        get_target_property(_sources "${_target}" SOURCES)
        if(_kind STREQUAL "ws_transport" AND NOT CONFIG_WS_TRANSPORT)
            continue()
        endif()
        set(_generated "${CMAKE_BINARY_DIR}/gea_${_kind}_patched.c")
        execute_process(COMMAND "${Python3_EXECUTABLE}"
            "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/patch_streaming_dependencies.py"
            "${_kind}" "${_dir}/${_relative}" "${_generated}"
            RESULT_VARIABLE _result)
        if(NOT _result EQUAL 0)
            message(FATAL_ERROR "Gea ${_kind} SDK patch failed; source version must be reviewed")
        endif()
        set(_replacement "")
        set(_found FALSE)
        foreach(_source IN LISTS _sources)
            if(_source STREQUAL "${_relative}" OR _source STREQUAL "${_dir}/${_relative}")
                list(APPEND _replacement "${_generated}")
                set(_found TRUE)
            else()
                list(APPEND _replacement "${_source}")
            endif()
        endforeach()
        if(NOT _found)
            message(FATAL_ERROR "Could not locate ${_relative} in ${_target}")
        endif()
        set_property(TARGET "${_target}" PROPERTY SOURCES "${_replacement}")
        target_include_directories("${_target}" PRIVATE "${_dir}")
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
            "${_dir}/${_relative}"
            "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/patch_streaming_dependencies.py")
        message(STATUS "Gea ${_kind}: streaming dependency patch enabled")
    endforeach()
endfunction()
