# Exercise a CLI configure, an inherited override, and a direct build fallback.
set(GEA_EMBEDDED_CAPABILITY_NETWORK 1 CACHE STRING "")
set(GEA_EMBEDDED_CAPABILITY_AUDIO 1 CACHE STRING "")
set(GEA_EMBEDDED_CAPABILITY_BLE 0 CACHE STRING "")
set(GEA_EMBEDDED_CAPABILITY_RTC 0 CACHE STRING "")
set(GEA_EMBEDDED_CAPABILITY_H264 0 CACHE STRING "")
foreach(capability NETWORK AUDIO BLE RTC H264)
  unset(ENV{GEA_EMBEDDED_CAPABILITY_${capability}})
endforeach()
include("${CMAKE_CURRENT_LIST_DIR}/../app_project.cmake")
if(NOT "$ENV{GEA_EMBEDDED_CAPABILITY_BLE}" STREQUAL "0")
  message(FATAL_ERROR "Reconfigure enabled BLE despite cached app analysis")
endif()
if(NOT "$ENV{GEA_EMBEDDED_CAPABILITY_AUDIO}" STREQUAL "1")
  message(FATAL_ERROR "Reconfigure lost audio capability")
endif()
set(ENV{GEA_EMBEDDED_CAPABILITY_BLE} "1")
include("${CMAKE_CURRENT_LIST_DIR}/../app_project.cmake")
if(NOT "$ENV{GEA_EMBEDDED_CAPABILITY_BLE}" STREQUAL "1")
  message(FATAL_ERROR "Explicit environment override ignored")
endif()
unset(ENV{GEA_EMBEDDED_CAPABILITY_BLE})
unset(GEA_EMBEDDED_CAPABILITY_BLE CACHE)
include("${CMAKE_CURRENT_LIST_DIR}/../app_project.cmake")
if(NOT "$ENV{GEA_EMBEDDED_CAPABILITY_BLE}" STREQUAL "1")
  message(FATAL_ERROR "Direct build fallback changed")
endif()
foreach(capability RTC H264)
  if(NOT "$ENV{GEA_EMBEDDED_CAPABILITY_${capability}}" STREQUAL "0")
    message(FATAL_ERROR "Reconfigure enabled ${capability} despite cached exclusion")
  endif()
  set(ENV{GEA_EMBEDDED_CAPABILITY_${capability}} "1")
  include("${CMAKE_CURRENT_LIST_DIR}/../app_project.cmake")
  if(NOT "$ENV{GEA_EMBEDDED_CAPABILITY_${capability}}" STREQUAL "1")
    message(FATAL_ERROR "Explicit ${capability} environment override ignored")
  endif()
  unset(ENV{GEA_EMBEDDED_CAPABILITY_${capability}})
  unset(GEA_EMBEDDED_CAPABILITY_${capability} CACHE)
  include("${CMAKE_CURRENT_LIST_DIR}/../app_project.cmake")
  if(NOT "$ENV{GEA_EMBEDDED_CAPABILITY_${capability}}" STREQUAL "1")
    message(FATAL_ERROR "Direct ${capability} build fallback changed")
  endif()
endforeach()
message(STATUS "Capability reconfiguration preserves cached analysis")
