# Exercise the board-default selection code itself without configuring ESP-IDF.
file(READ "${CMAKE_CURRENT_LIST_DIR}/../../esp32-s3-touch-amoled-1.8/main/CMakeLists.txt" source)
string(FIND "${source}" "set(_GEA_BOARD_DISPLAY_DEFAULTS" start)
string(SUBSTRING "${source}" ${start} -1 tail)
string(FIND "${tail}" "target_compile_definitions(" length)
string(SUBSTRING "${source}" ${start} ${length} selection)
set(GEA_BOARD_DISPLAY_WIDTH 450)
set(GEA_BOARD_DISPLAY_HEIGHT 600)
set(GEA_BOARD_NATIVE_DISPLAY_WIDTH 450)
set(GEA_BOARD_NATIVE_DISPLAY_HEIGHT 600)
set(GEA_EMBEDDED_APP_DEFINES "")
cmake_language(EVAL CODE "${selection}")
list(LENGTH _GEA_BOARD_DISPLAY_DEFINITIONS count)
if(NOT count EQUAL 4)
    message(FATAL_ERROR "Default board lost its four dimensions")
endif()
set(GEA_EMBEDDED_APP_DEFINES GEA_EMBEDDED_DISPLAY_WIDTH=600 GEA_EMBEDDED_DISPLAY_HEIGHT=450)
cmake_language(EVAL CODE "${selection}")
set(expected GEA_EMBEDDED_DISPLAY_NATIVE_WIDTH=450 GEA_EMBEDDED_DISPLAY_NATIVE_HEIGHT=600)
if(NOT "${_GEA_BOARD_DISPLAY_DEFINITIONS}" STREQUAL "${expected}")
    message(FATAL_ERROR "Landscape dimensions were overridden by board defaults")
endif()
list(APPEND GEA_EMBEDDED_APP_DEFINES GEA_EMBEDDED_DISPLAY_NATIVE_WIDTH=450 GEA_EMBEDDED_DISPLAY_NATIVE_HEIGHT=600)
cmake_language(EVAL CODE "${selection}")
if(_GEA_BOARD_DISPLAY_DEFINITIONS)
    message(FATAL_ERROR "App dimensions have duplicate board definitions")
endif()
